### PR TITLE
Discord team registration stuck on hacker room

### LINKED ISSUE #274: [Bug] - Discord team registration stuck on hacker room
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description
Team registration doesn't end after you add your team room

## Expected Behavior
After adding your team name it should show details and end the flow

## Actual Behavior
It shows the details and then new input is treated as the hack room name

## Steps to Reproduce
Register team, follow steps, after details are sent, send another message

## Other Information
image

### PR DESCRIPTION
**Pull request by RazvanPreotu99**
## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Commented the lines setting the DiscordContext currentCommand and nextStep to undefined at the end of teamChannel. Instead called clear() method.

## Related Issues

Closes #274 - team registration stuck on hacker room.

Co-authored-by: Michael Nguyen <50305984+mkn170030@users.noreply.github.com>

### CODE REVIEW

**Review by SpencerKaiser — COMMENTED** [review]
Please revert the deletion of `.env.sample`; we need that file 😉

File: src/discord/events/message/registerTeam.ts [hunk 1]
```diff
@@ -121,9 +121,10 @@ export const regSubCommands: SubCommands = {
           ],
         },
       });
-      ctx.currentCommand = undefined;
-      ctx.nextStep = undefined;
+      // ctx.currentCommand = undefined;
+      // ctx.nextStep = undefined;
```
Comment (SpencerKaiser) [inline src/discord/events/message/registerTeam.ts:125]: So this was the issue? Can you delete both of these comments? Do the tests still pass?

Comment (RazvanPreotu99) [reply src/discord/events/message/registerTeam.ts:125]: Yes, after registering the team the bot no longer thinks the next message is the team room. The registerTeam.tests.ts does not pass because it checks if those properties are undefined. Is this alright?

File: src/discord/events/message/registerTeam.ts [hunk 2]
```diff
@@ -121,9 +121,10 @@ export const regSubCommands: SubCommands = {
...
       await ctx.save();
+      ctx.clear();
```
Comment (SpencerKaiser) [inline src/discord/events/message/registerTeam.ts:127]:
```suggestion
      await ctx.clear();
```

File: src/discord/events/message/registerTeam.ts [hunk 3]
```diff
@@ -121,9 +121,10 @@ export const regSubCommands: SubCommands = {
           ],
         },
       });
-      ctx.currentCommand = undefined;
-      ctx.nextStep = undefined;
+      // ctx.currentCommand = undefined;
+      // ctx.nextStep = undefined;
       await ctx.save();
```
Comment (SpencerKaiser) [inline src/discord/events/message/registerTeam.ts:126]: Investigate whether this method does the same thing as the three lines above; if so, remove this

File: .env.sample [hunk 4]
```diff
@@ -17,4 +17,4 @@ CHALLENGE_URL="https://your-sponsor-challenge.com"
 
 # Only uncomment and use these if you have a custom user/pass for your Postgres Server
 #PGUSER=""
-#PGPASSWORD=""
+#PGPASSWORD=""
```
Comment (SpencerKaiser) [inline .env.sample:20]:
```suggestion
#PGPASSWORD=""

```

**Review by SpencerKaiser — APPROVED** [review]

**Comment by SpencerKaiser** [comment]
@RazvanPreotu99 can you add @mkn170030's `Co-authored-by` to the description? Otherwise this is ready to go!

**Comment by RazvanPreotu99** [comment]
> @RazvanPreotu99 can you add @mkn170030's `Co-authored-by` to the description? Otherwise this is ready to go!

**Comment by RazvanPreotu99** [comment]
Sorry I misclicked. Updated coauthors so it should be good now.
